version: "3.5"
services:
    client:
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
        links:
            - api
        networks:
            - webappnetwork
    api:
        build: ./api
        container_name: node-tutorial-api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
        depends_on:
            - mongodb
        networks:
            - webappnetwork
        environment:
            WAIT_HOSTS: mongodb:27017
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
